### PR TITLE
Fixed Navbar

### LINKED ISSUE #5: Fix Navbar
Add the version responsive in the current NavBar (We are using Bootstrap v4)

### PR DESCRIPTION
**Pull request by arendondiosa**
Fixes #5 

Screen Shot 2020-08-23 at 3 25 19 PM
Screen Shot 2020-08-23 at 3 25 33 PM
Screen Shot 2020-08-23 at 3 25 40 PM

### CODE REVIEW

File: assets/static/js/navbar.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
+$(document).ready(function () {
+  const height = $(window).height();
+
+  $(".scrollable-menu").css("max-height", height);
+
+  // Style menu responsive
+  $(".navbar-toggler").on("click", function () {
```
Comment (jonathanvm13) [inline assets/static/js/navbar.js:7]: so bootstrap navbar is not responsible by default so that's the reason this snipped is needed, right ?

**Review by jonathanvm13 — CHANGES_REQUESTED** [review]

File: assets/static/js/navbar.js (hunk 1 above)
Comment (arendondiosa) [reply assets/static/js/navbar.js:7]: `$(".scrollable-menu").css("max-height", height);` - Display a full size menu when there are a long list of links. This is a customization because the original implementation hides the last items

`$(".navbar-toggler").on("click", function () {` - We need to add some custom classes for menu when is displayed. For example, the color in the menu button is changed because the background pass from dark to light

**Review by jonathanvm13 — DISMISSED** [review]
